name: Publish to GitHub Packages

# As we cannot automatically run tests with GH Actions due to a dependency on MagicDraw,
# you will need to manually check that all tests pass and then create a release on Github,
# which will trigger this workflow.
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode -f pom-plain.xml -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
